/**
 * Complete Slicker Carousel class (Slick-compatible)
 * Imports all modules and methods
 */
import type { SlickOptions, TouchObject, SlickBreakpointSettings } from '../types';
import * as CoreMethods from './methods';
import * as SlideLogic from './slide-logic';
import * as Animations from '../modules/animations';
import * as Arrows from '../modules/arrows';
import * as Dots from '../modules/dots';
import * as Keyboard from '../modules/keyboard';
import * as Touch from '../modules/touch';
import * as Lazy from '../modules/lazy';
import * as Responsive from '../modules/responsive';
import * as Accessibility from '../modules/accessibility';
import * as PublicMethods from './public-methods';
export declare class Slick {
    defaults: SlickOptions;
    options: SlickOptions;
    originalSettings: SlickOptions;
    animating: boolean;
    dragging: boolean;
    autoPlayTimer: number | null;
    currentDirection: number;
    currentLeft: number | null;
    currentSlide: number;
    direction: number;
    $dots: HTMLElement | null;
    listWidth: number | null;
    listHeight: number | null;
    loadIndex: number;
    $nextArrow: HTMLElement | null;
    $prevArrow: HTMLElement | null;
    scrolling: boolean;
    slideCount: number | null;
    slideWidth: number | null;
    $slideTrack: HTMLElement | null;
    $slides: HTMLElement[];
    sliding: boolean;
    slideOffset: number;
    swipeLeft: number | null;
    swiping: boolean;
    $list: HTMLElement | null;
    touchObject: TouchObject;
    transformsEnabled: boolean;
    unslicked: boolean;
    activeBreakpoint: number | null;
    animType: string | null;
    animProp: string | null;
    breakpoints: number[];
    breakpointSettings: SlickBreakpointSettings;
    cssTransitions: boolean;
    focussed: boolean;
    interrupted: boolean;
    hidden: string;
    paused: boolean;
    positionProp: string | null;
    respondTo: 'window' | 'slider' | 'min' | null;
    rowCount: number;
    shouldClick: boolean;
    $slider: HTMLElement;
    $slidesCache: HTMLElement[] | null;
    transformType: string | null;
    transitionType: string | null;
    visibilityChange: string;
    windowWidth: number;
    windowTimer: number | null;
    instanceUid: number;
    htmlExpr: RegExp;
    isInitializing: boolean;
    inResponsiveRefresh: boolean;
    boundAutoPlay: () => void;
    boundAutoPlayClear: () => void;
    boundAutoPlayIterator: () => void;
    boundChangeSlide: (event: Event, dontAnimate?: boolean) => void;
    boundClickHandler: (event: Event) => void;
    boundSelectHandler: (event: Event) => void;
    boundSetPosition: () => void;
    boundSwipeHandler: (event: Event) => void;
    boundDragHandler: (event: Event) => void;
    boundKeyHandler: (event: KeyboardEvent) => void;
    boundResize: () => void;
    boundOrientationChange: () => void;
    boundVisibility: () => void;
    preventDefault: (event: Event) => void;
    constructor(element: HTMLElement, settings?: Partial<SlickOptions>);
    init: (this: Slick, creation?: boolean) => void;
    buildRows: (this: Slick) => void;
    buildOut: (this: Slick) => void;
    setProps: (this: Slick) => void;
    registerBreakpoints: (this: Slick) => void;
    setupInfinite: typeof CoreMethods.setupInfinite;
    setSlideClasses: typeof CoreMethods.setSlideClasses;
    startLoad: typeof CoreMethods.startLoad;
    loadSlider: typeof CoreMethods.loadSlider;
    initUI: typeof CoreMethods.initUI;
    setDimensions: typeof CoreMethods.setDimensions;
    setHeight: typeof CoreMethods.setHeight;
    setPosition: typeof CoreMethods.setPosition;
    resize: typeof CoreMethods.resize;
    autoPlay: typeof CoreMethods.autoPlay;
    autoPlayClear: (this: Slick) => void;
    autoPlayIterator: typeof CoreMethods.autoPlayIterator;
    lazyLoad: typeof Lazy.lazyLoad;
    progressiveLazyLoad: typeof Lazy.progressiveLazyLoad;
    getLeft: typeof SlideLogic.getLeft;
    slideHandler: typeof SlideLogic.slideHandler;
    postSlide: typeof SlideLogic.postSlide;
    changeSlide: typeof SlideLogic.changeSlide;
    selectHandler: typeof SlideLogic.selectHandler;
    getNavTarget: typeof SlideLogic.getNavTarget;
    asNavFor: typeof SlideLogic.asNavFor;
    initializeEvents: typeof SlideLogic.initializeEvents;
    animateSlide: typeof Animations.animateSlide;
    animateHeight: typeof Animations.animateHeight;
    applyTransition: typeof Animations.applyTransition;
    disableTransition: typeof Animations.disableTransition;
    fadeSlide: typeof Animations.fadeSlide;
    fadeSlideOut: typeof Animations.fadeSlideOut;
    setCSS: typeof Animations.setCSS;
    setFade: typeof Animations.setFade;
    buildArrows: typeof Arrows.buildArrows;
    updateArrows: typeof Arrows.updateArrows;
    initArrowEvents: typeof Arrows.initArrowEvents;
    buildDots: typeof Dots.buildDots;
    updateDots: typeof Dots.updateDots;
    getDotCount: typeof Dots.getDotCount;
    initDotEvents: typeof Dots.initDotEvents;
    interrupt: typeof Dots.interrupt;
    keyHandler: typeof Keyboard.keyHandler;
    swipeHandler: typeof Touch.swipeHandler;
    swipeStart: typeof Touch.swipeStart;
    swipeMove: typeof Touch.swipeMove;
    swipeEnd: typeof Touch.swipeEnd;
    swipeDirection: typeof Touch.swipeDirection;
    getSlideCount: typeof Touch.getSlideCount;
    checkNavigable: typeof Touch.checkNavigable;
    getNavigableIndexes: typeof Touch.getNavigableIndexes;
    dragHandler: (this: Slick, _event: Event) => void;
    checkResponsive: typeof Responsive.checkResponsive;
    initADA: typeof Accessibility.initADA;
    activateADA: typeof Accessibility.activateADA;
    focusHandler: typeof Accessibility.focusHandler;
    slickAdd: typeof PublicMethods.slickAdd;
    addSlide: typeof PublicMethods.slickAdd;
    slickRemove: typeof PublicMethods.slickRemove;
    removeSlide: typeof PublicMethods.slickRemove;
    slickFilter: typeof PublicMethods.slickFilter;
    filterSlides: typeof PublicMethods.slickFilter;
    slickUnfilter: typeof PublicMethods.slickUnfilter;
    unfilterSlides: typeof PublicMethods.slickUnfilter;
    slickSetOption: typeof PublicMethods.slickSetOption;
    setOption: typeof PublicMethods.slickSetOption;
    unload: typeof PublicMethods.unload;
    destroy: typeof PublicMethods.destroy;
    cleanUpRows: typeof PublicMethods.cleanUpRows;
    cleanUpEvents: typeof PublicMethods.cleanUpEvents;
    reinit: typeof PublicMethods.reinit;
    cleanUpSlideEvents: typeof PublicMethods.cleanUpSlideEvents;
    initSlideEvents: typeof PublicMethods.initSlideEvents;
    refresh: typeof PublicMethods.refresh;
    slickGoTo(slide: number, dontAnimate?: boolean): void;
    goTo: (slide: number, dontAnimate?: boolean) => void;
    slickNext(): void;
    next: () => void;
    slickPrev(): void;
    prev: () => void;
    slickPause(): void;
    pause: () => void;
    slickPlay(): void;
    play: () => void;
    slickCurrentSlide(): number;
    getCurrent: () => number;
    slickGetOption(option: keyof SlickOptions): string | number | boolean | HTMLElement | ((slider: any, i: number) => HTMLElement) | import("../types").ResponsiveSettings[] | null;
    getOption: (option: keyof SlickOptions) => string | number | boolean | HTMLElement | ((slider: any, i: number) => HTMLElement) | import("../types").ResponsiveSettings[] | null;
    getSlick(): this;
    unslick(fromBreakpoint?: number): void;
    clickHandler(event: Event): void;
    orientationChange(): void;
    visibility(): void;
}
